on: workflow_dispatch

steps:
- uses: s4u/maven-settings-action@v3.0.0
  with:
    servers: |
      [{
        "id": "reposilite-repository",
        "username": "${{ secrets.MAVEN_NAME }}",
        "password": "${{ secrets.MAVEN_SECRET }}"
      }]
